title: Frank Li # your name (or website title) here
logo: "/images/logo_circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst @ Aborn & Co.
  <br><br>
  Head of R&D, University of Memphis Tigers Men's Basketball Analytics
  <br><br>
  Rice University '20
  <br>
  BA Computer Science & Sport Management
  <br><br>
  <a href="https://www.twitter.com/hzblacksmith">Twitter</a>
  <br><br>
  <a href="https://www.linkedin.com/in/lifan-frank-li/">LinkedIn</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-176822747-1 # your Google Analytics tracking ID here
