title: Frank Li # your name (or website title) here
logo: "/images/logo_circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Thank you so much for visiting my portfolio! 
  From Hangzhou, China, I am a senior at Rice University studying sport management and computer science. As a fanatic sports fan who is interested in every aspect of sports, I enjoy utilizing my data analytics and communication skills to provide some insights for sports from both performance side and business side. I aspire to bridge between the U.S. and China by utilizing my bilingual and bi-cultural abilities, especially in the language of sports!
  Please do not hesitate to reach out to me if you have any question! 
  <br><br>
  <a href="https://www.linkedin.com/in/lifan-frank-li/">LinkedIn</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
